version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: desamart-db
    restart: always
    environment:
      POSTGRES_USER: desamart
      POSTGRES_PASSWORD: desamart123
      POSTGRES_DB: desamart
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: desamart-backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://desamart:desamart123@db:5432/desamart?schema=public
      JWT_SECRET: rahasia123
      PORT: 8000
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  postgres_data: